site_name: RingCentral Engage Developer Guide
site_url: https://engage-api-docs.rtfd.org
site_favicon: favicon.ico
repo_url: https://github.com/ringcentral/engage-api-docs
docs_dir: docs
theme:
  name: moonstone
  custom_dir: 'theme/'
  fluid_layout: True
  suppress_nextprev: true
  shortcuts:
    - foo

plugins:
  - git-committers:
      repository: ringcentral/engage-api-docs
      branch: master
  - bootstrap-tables

markdown_extensions:
  - markdown.extensions.admonition
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.superfences
  - codehilite:
      linenums: "None"

#extra_css: [extra.css]
#extra_javascript: [fonts.js]
pages:
- 'Primary':
  - 'Interactions':
    - 'Overview': interactions/index.md
    - 'Getting Started':
      - 'Node JS': interactions/quick-start/node.md
      - 'PHP': interactions/quick-start/php.md
      - 'Python': interactions/quick-start/python.md
      - 'Ruby': interactions/quick-start/ruby.md
    - 'Chatbots':
      - 'Overview': interactions/chatbots/overview.md
      - 'Implementation': interactions/chatbots/implementation.md
      - 'Replying to Messages': interactions/chatbots/replies.md
      - 'Creating Interventions': interactions/chatbots/interventions.md
      - 'Transferring to an Agent': interactions/chatbots/transfers.md
      - 'Closing Threads': interactions/chatbots/threads.md
  - 'Routing':
    - 'Overview': routing/index.md
    - 'Getting Started':
      - 'Node JS': routing/quick-start/node.md
      - 'PHP': routing/quick-start/php.md
      - 'Python': routing/quick-start/python.md
      - 'Ruby': routing/quick-start/ruby.md
- 'Secondary':
  - 'Using the API':
    - 'Requests': basics/requests.md
    - 'Responses and Errors': basics/responses.md
    - 'Authentication': basics/auth.md
    - 'Uploading Files': basics/uploads.md
    - 'Filters and Pagination': basics/pagination.md
    - 'User Impersonation': basics/impersonation.md
  - 'Events and Notifications':
    - 'Overview': webhooks/overview.md
    - 'Creating Webhooks': webhooks/create.md
    - 'Receiving Events': webhooks/receive.md
    - 'Event Types': webhooks/events.md
  - 'SDKs': sdks.md
